/**
 * Camada de dados de demonstração — DeskControl
 * Usada quando o Supabase não está configurado (modo dev/demo).
 * Permite que a UI seja totalmente funcional para preview visual.
 */

import type {
  OSResumo,
  ClienteResumo,
  StatusOS,
  PrioridadeOS,
  ResumoFinanceiro,
} from "@/types";

export const demoUser = {
  id: "demo-user",
  empresaId: "demo-empresa",
  nome: "Administrador (Demo)",
  email: "admin@deskcontrol.demo",
  role: "admin" as const,
  status: "ativo" as const,
  avatarUrl: undefined,
  telefone: undefined,
  ultimoAcesso: undefined,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const demoEmpresa = {
  id: "demo-empresa",
  nome: "TechRepair Assistência",
  slug: "techrepair",
  plano: "pro" as const,
  status: "trial" as const,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const demoResumoFinanceiro: ResumoFinanceiro = {
  receitaMes: 18750,
  despesaMes: 8320,
  saldoMes: 10430,
  aReceber: 6200,
  aPagar: 3100,
  ticketMedio: 312.5,
};

const hoje = new Date();
const diasAtras = (n: number) =>
  new Date(hoje.getTime() - n * 86400000).toISOString();

/* ---------------------- Ordens de Serviço ---------------------- */

export const demoOS: OSResumo[] = [
  {
    id: "os-1",
    numero: "OS-2026-0042",
    clienteNome: "Maria Aparecida Souza",
    equipamentoNome: "Notebook Dell Inspiron 15",
    status: "em_reparo",
    prioridade: "alta",
    tecnicoNome: "Carlos Mendes",
    valorTotal: 450,
    dataAbertura: diasAtras(2),
    dataPrevisao: diasAtras(-1),
  },
  {
    id: "os-2",
    numero: "OS-2026-0041",
    clienteNome: "João Pedro Almeida",
    equipamentoNome: "iPhone 13 Pro",
    status: "aguardando_aprovacao",
    prioridade: "media",
    tecnicoNome: "Ana Ribeiro",
    valorTotal: 280,
    dataAbertura: diasAtras(3),
    dataPrevisao: diasAtras(-2),
  },
  {
    id: "os-3",
    numero: "OS-2026-0040",
    clienteNome: "Construtora Horizonte Ltda",
    equipamentoNome: "DVR CFTV 16 canais",
    status: "pronto",
    prioridade: "urgente",
    tecnicoNome: "Carlos Mendes",
    valorTotal: 1200,
    dataAbertura: diasAtras(5),
    dataPrevisao: diasAtras(0),
  },
  {
    id: "os-4",
    numero: "OS-2026-0039",
    clienteNome: "Fernanda Costa Lima",
    equipamentoNome: "Samsung Galaxy S22",
    status: "em_diagnostico",
    prioridade: "baixa",
    tecnicoNome: undefined,
    valorTotal: 0,
    dataAbertura: diasAtras(1),
    dataPrevisao: undefined,
  },
  {
    id: "os-5",
    numero: "OS-2026-0038",
    clienteNome: "Ricardo Hoffmann",
    equipamentoNome: "Notebook Lenovo ThinkPad",
    status: "entregue",
    prioridade: "media",
    tecnicoNome: "Ana Ribeiro",
    valorTotal: 650,
    dataAbertura: diasAtras(10),
    dataPrevisao: diasAtras(-3),
  },
  {
    id: "os-6",
    numero: "OS-2026-0037",
    clienteNome: "Padaria Pão Quente",
    equipamentoNome: "Forno Industrial",
    status: "aguardando_pecas",
    prioridade: "alta",
    tecnicoNome: "Carlos Mendes",
    valorTotal: 890,
    dataAbertura: diasAtras(7),
    dataPrevisao: diasAtras(-5),
  },
  {
    id: "os-7",
    numero: "OS-2026-0036",
    clienteNome: "Patrícia Nunes",
    equipamentoNome: "Máquina de Lavar Brastemp",
    status: "aberta",
    prioridade: "baixa",
    tecnicoNome: undefined,
    valorTotal: 0,
    dataAbertura: diasAtras(0),
    dataPrevisao: undefined,
  },
  {
    id: "os-8",
    numero: "OS-2026-0035",
    clienteNome: "Roberto Sérgio Mota",
    equipamentoNome: "PlayStation 5",
    status: "cancelada",
    prioridade: "media",
    tecnicoNome: "Ana Ribeiro",
    valorTotal: 0,
    dataAbertura: diasAtras(15),
    dataPrevisao: undefined,
  },
];

/* ---------------------- Clientes ---------------------- */

export const demoClientes: ClienteResumo[] = [
  {
    id: "cli-1",
    nome: "Maria Aparecida Souza",
    telefone: "(11) 98765-4321",
    whatsapp: "(11) 98765-4321",
    totalOs: 8,
    ultimaOs: diasAtras(2),
  },
  {
    id: "cli-2",
    nome: "João Pedro Almeida",
    telefone: "(11) 91234-5678",
    whatsapp: "(11) 91234-5678",
    totalOs: 3,
    ultimaOs: diasAtras(3),
  },
  {
    id: "cli-3",
    nome: "Construtora Horizonte Ltda",
    telefone: "(11) 3000-2000",
    whatsapp: "(11) 99000-1000",
    totalOs: 15,
    ultimaOs: diasAtras(5),
  },
  {
    id: "cli-4",
    nome: "Fernanda Costa Lima",
    telefone: "(11) 95555-1234",
    whatsapp: "(11) 95555-1234",
    totalOs: 2,
    ultimaOs: diasAtras(1),
  },
  {
    id: "cli-5",
    nome: "Padaria Pão Quente",
    telefone: "(11) 2222-3333",
    whatsapp: undefined,
    totalOs: 6,
    ultimaOs: diasAtras(7),
  },
  {
    id: "cli-6",
    nome: "Roberto Sérgio Mota",
    telefone: "(11) 97777-8888",
    whatsapp: "(11) 97777-8888",
    totalOs: 4,
    ultimaOs: diasAtras(15),
  },
  {
    id: "cli-7",
    nome: "Ricardo Hoffmann",
    telefone: "(11) 94444-5555",
    whatsapp: "(11) 94444-5555",
    totalOs: 5,
    ultimaOs: diasAtras(10),
  },
  {
    id: "cli-8",
    nome: "Patrícia Nunes",
    telefone: "(11) 93333-2222",
    whatsapp: "(11) 93333-2222",
    totalOs: 1,
    ultimaOs: diasAtras(0),
  },
];

/* ---------------------- Equipamentos ---------------------- */

export const demoEquipamentos = [
  {
    id: "equip-1",
    clienteId: "cli-1",
    clienteNome: "Maria Aparecida Souza",
    nome: "Notebook Dell Inspiron 15",
    marca: "Dell",
    modelo: "Inspiron 15 3000",
    numero_serie: "SN-DELL-12345",
    imei: null,
    cor: "Preto",
    totalOs: 3,
    ultimaOs: diasAtras(2),
    status: "em_reparo" as StatusOS,
  },
  {
    id: "equip-2",
    clienteId: "cli-2",
    clienteNome: "João Pedro Almeida",
    nome: "iPhone 13 Pro",
    marca: "Apple",
    modelo: "iPhone 13 Pro 256GB",
    numero_serie: "SN-APPLE-67890",
    imei: "358123456789012",
    cor: "Grafite",
    totalOs: 2,
    ultimaOs: diasAtras(3),
    status: "aguardando_aprovacao" as StatusOS,
  },
  {
    id: "equip-3",
    clienteId: "cli-3",
    clienteNome: "Construtora Horizonte Ltda",
    nome: "DVR CFTV 16 canais",
    marca: "Intelbras",
    modelo: "MHDX 3116",
    numero_serie: "SN-INTEL-11111",
    imei: null,
    cor: "Preto",
    totalOs: 5,
    ultimaOs: diasAtras(5),
    status: "pronto" as StatusOS,
  },
  {
    id: "equip-4",
    clienteId: "cli-4",
    clienteNome: "Fernanda Costa Lima",
    nome: "Samsung Galaxy S22",
    marca: "Samsung",
    modelo: "Galaxy S22 128GB",
    numero_serie: "SN-SAMS-22222",
    imei: "357234567890123",
    cor: "Branco",
    totalOs: 1,
    ultimaOs: diasAtras(1),
    status: "em_diagnostico" as StatusOS,
  },
  {
    id: "equip-5",
    clienteId: "cli-7",
    clienteNome: "Ricardo Hoffmann",
    nome: "Notebook Lenovo ThinkPad",
    marca: "Lenovo",
    modelo: "ThinkPad E14 Gen 4",
    numero_serie: "SN-LENO-33333",
    imei: null,
    cor: "Preto",
    totalOs: 3,
    ultimaOs: diasAtras(10),
    status: "entregue" as StatusOS,
  },
  {
    id: "equip-6",
    clienteId: "cli-5",
    clienteNome: "Padaria Pão Quente",
    nome: "Forno Industrial",
    marca: "Prática",
    modelo: "Turbo Express 1.000",
    numero_serie: "SN-PRAT-44444",
    imei: null,
    cor: "Aço inox",
    totalOs: 2,
    ultimaOs: diasAtras(7),
    status: "aguardando_pecas" as StatusOS,
  },
  {
    id: "equip-7",
    clienteId: "cli-8",
    clienteNome: "Patrícia Nunes",
    nome: "Máquina de Lavar Brastemp",
    marca: "Brastemp",
    modelo: "Clean BWK11AB 11kg",
    numero_serie: "SN-BRAS-55555",
    imei: null,
    cor: "Branco",
    totalOs: 1,
    ultimaOs: diasAtras(0),
    status: "aberta" as StatusOS,
  },
  {
    id: "equip-8",
    clienteId: "cli-6",
    clienteNome: "Roberto Sérgio Mota",
    nome: "PlayStation 5",
    marca: "Sony",
    modelo: "PS5 825GB",
    numero_serie: "SN-SONY-66666",
    imei: null,
    cor: "Branco",
    totalOs: 1,
    ultimaOs: diasAtras(15),
    status: "cancelada" as StatusOS,
  },
];

/* ---------------------- Usuários ---------------------- */

export const demoUsuarios = [
  {
    id: "usr-1",
    nome: "Administrador (Demo)",
    email: "admin@deskcontrol.demo",
    role: "admin",
    status: "ativo",
    telefone: "(11) 99999-0000",
    avatar_url: null,
    totalOs: 0,
    ultimoAcesso: diasAtras(0),
    createdAt: diasAtras(90),
  },
  {
    id: "usr-2",
    nome: "Carlos Mendes",
    email: "carlos@techrepair.demo",
    role: "tecnico",
    status: "ativo",
    telefone: "(11) 98888-1111",
    avatar_url: null,
    totalOs: 24,
    ultimoAcesso: diasAtras(0),
    createdAt: diasAtras(60),
  },
  {
    id: "usr-3",
    nome: "Ana Ribeiro",
    email: "ana@techrepair.demo",
    role: "tecnico",
    status: "ativo",
    telefone: "(11) 97777-2222",
    avatar_url: null,
    totalOs: 18,
    ultimoAcesso: diasAtras(1),
    createdAt: diasAtras(45),
  },
  {
    id: "usr-4",
    nome: "Pedro Atendente",
    email: "pedro@techrepair.demo",
    role: "atendente",
    status: "ativo",
    telefone: "(11) 96666-3333",
    avatar_url: null,
    totalOs: 0,
    ultimoAcesso: diasAtras(0),
    createdAt: diasAtras(30),
  },
  {
    id: "usr-5",
    nome: "Financeiro Silva",
    email: "financeiro@techrepair.demo",
    role: "financeiro",
    status: "inativo",
    telefone: "(11) 95555-4444",
    avatar_url: null,
    totalOs: 0,
    ultimoAcesso: diasAtras(10),
    createdAt: diasAtras(20),
  },
];

/* ---------------------- Orçamentos ---------------------- */

export const demoOrcamentos = [
  {
    id: "orc-1",
    numero: "ORC-2026-0018",
    clienteId: "cli-1",
    clienteNome: "João Pedro Almeida",
    equipamentoNome: "iPhone 13 Pro",
    titulo: "Troca de tela + bateria — iPhone 13 Pro",
    status: "enviado",
    valorTotal: 480,
    valorDesconto: 0,
    dataValidade: diasAtras(-5),
    dataCriacao: diasAtras(3),
    dataEnvio: diasAtras(2),
    dataAprovacao: null,
    linkAprovacao: "https://deskcontrol.app/aprovar/orc-1-abc123",
    observacoes: "Prazo estimado de 2 dias úteis após aprovação.",
    itens: [
      { descricao: "Display iPhone 13 Pro (original)", tipo: "peca", quantidade: 1, valorUnitario: 280 },
      { descricao: "Bateria iPhone 13 Pro", tipo: "peca", quantidade: 1, valorUnitario: 120 },
      { descricao: "Mão de obra troca de tela", tipo: "servico", quantidade: 1, valorUnitario: 80 },
    ],
  },
  {
    id: "orc-2",
    numero: "ORC-2026-0017",
    clienteId: "cli-2",
    clienteNome: "Construtora Horizonte Ltda",
    equipamentoNome: "DVR CFTV 16 canais",
    titulo: "Manutenção preventiva CFTV + substituição HDD",
    status: "aprovado",
    valorTotal: 1200,
    valorDesconto: 100,
    dataValidade: diasAtras(-10),
    dataCriacao: diasAtras(8),
    dataEnvio: diasAtras(7),
    dataAprovacao: diasAtras(5),
    linkAprovacao: null,
    observacoes: null,
    itens: [
      { descricao: "HD Seagate 4TB Surveillance", tipo: "peca", quantidade: 1, valorUnitario: 650 },
      { descricao: "Manutenção preventiva DVR", tipo: "servico", quantidade: 1, valorUnitario: 350 },
      { descricao: "Limpeza câmeras (8 unidades)", tipo: "servico", quantidade: 8, valorUnitario: 25 },
    ],
  },
  {
    id: "orc-3",
    numero: "ORC-2026-0016",
    clienteId: "cli-3",
    clienteNome: "Padaria Pão Quente",
    equipamentoNome: "Forno Industrial",
    titulo: "Revisão geral + troca de resistências",
    status: "reprovado",
    valorTotal: 2100,
    valorDesconto: 0,
    dataValidade: diasAtras(5),
    dataCriacao: diasAtras(12),
    dataEnvio: diasAtras(11),
    dataAprovacao: null,
    linkAprovacao: null,
    observacoes: "Cliente optou por não realizar o reparo.",
    itens: [
      { descricao: "Resistência tubular 3000W", tipo: "peca", quantidade: 2, valorUnitario: 480 },
      { descricao: "Revisão geral forno", tipo: "servico", quantidade: 1, valorUnitario: 640 },
      { descricao: "Mão de obra instalação", tipo: "servico", quantidade: 1, valorUnitario: 500 },
    ],
  },
  {
    id: "orc-4",
    numero: "ORC-2026-0015",
    clienteId: "cli-4",
    clienteNome: "Maria Aparecida Souza",
    equipamentoNome: "Notebook Dell Inspiron 15",
    titulo: "Troca DC Jack + limpeza interna",
    status: "aprovado",
    valorTotal: 225,
    valorDesconto: 25,
    dataValidade: diasAtras(-15),
    dataCriacao: diasAtras(20),
    dataEnvio: diasAtras(19),
    dataAprovacao: diasAtras(18),
    linkAprovacao: null,
    observacoes: null,
    itens: [
      { descricao: "DC Jack Dell Inspiron 15", tipo: "peca", quantidade: 1, valorUnitario: 75 },
      { descricao: "Mão de obra troca DC Jack", tipo: "servico", quantidade: 1, valorUnitario: 120 },
      { descricao: "Limpeza interna + pasta térmica", tipo: "servico", quantidade: 1, valorUnitario: 55 },
    ],
  },
  {
    id: "orc-5",
    numero: "ORC-2026-0014",
    clienteId: "cli-5",
    clienteNome: "Fernanda Costa Lima",
    equipamentoNome: "Samsung Galaxy S22",
    titulo: "Diagnóstico + estimativa de reparo",
    status: "rascunho",
    valorTotal: 0,
    valorDesconto: 0,
    dataValidade: null,
    dataCriacao: diasAtras(1),
    dataEnvio: null,
    dataAprovacao: null,
    linkAprovacao: null,
    observacoes: "Aguardando diagnóstico completo.",
    itens: [],
  },
];

/* ---------------------- Estoque ---------------------- */

export const demoProdutos = [
  {
    id: "prod-1",
    nome: "Display iPhone 13 Pro (original)",
    categoria: "Peças",
    marca: "Apple",
    codigo: "DISP-IP13P-OR",
    estoque: 3,
    estoqueMin: 2,
    valorCusto: 580,
    valorVenda: 890,
    unidade: "un",
  },
  {
    id: "prod-2",
    nome: "Bateria iPhone 13 Pro",
    categoria: "Peças",
    marca: "Apple",
    codigo: "BAT-IP13P",
    estoque: 8,
    estoqueMin: 3,
    valorCusto: 95,
    valorVenda: 180,
    unidade: "un",
  },
  {
    id: "prod-3",
    nome: "DC Jack Notebook Dell 7.4mm",
    categoria: "Peças",
    marca: "Dell",
    codigo: "DCJ-DELL-74",
    estoque: 12,
    estoqueMin: 5,
    valorCusto: 25,
    valorVenda: 45,
    unidade: "un",
  },
  {
    id: "prod-4",
    nome: "Pasta Térmica Noctua NT-H1",
    categoria: "Insumos",
    marca: "Noctua",
    codigo: "PAST-NTH1",
    estoque: 1,
    estoqueMin: 3,
    valorCusto: 28,
    valorVenda: 55,
    unidade: "un",
  },
  {
    id: "prod-5",
    nome: "SSD Kingston 480GB SATA",
    categoria: "Peças",
    marca: "Kingston",
    codigo: "SSD-KING-480",
    estoque: 5,
    estoqueMin: 2,
    valorCusto: 180,
    valorVenda: 290,
    unidade: "un",
  },
  {
    id: "prod-6",
    nome: "Memória RAM DDR4 8GB 3200MHz",
    categoria: "Peças",
    marca: "Kingston",
    codigo: "RAM-DDR4-8-32",
    estoque: 7,
    estoqueMin: 3,
    valorCusto: 95,
    valorVenda: 160,
    unidade: "un",
  },
  {
    id: "prod-7",
    nome: "Tela Samsung S22 AMOLED",
    categoria: "Peças",
    marca: "Samsung",
    codigo: "TELA-S22-AM",
    estoque: 0,
    estoqueMin: 1,
    valorCusto: 320,
    valorVenda: 580,
    unidade: "un",
  },
  {
    id: "prod-8",
    nome: "Álcool Isopropílico 99% 1L",
    categoria: "Insumos",
    marca: "Genérico",
    codigo: "ALCOOL-99-1L",
    estoque: 4,
    estoqueMin: 2,
    valorCusto: 18,
    valorVenda: 35,
    unidade: "un",
  },
];

/* ---------------------- Contratos ---------------------- */

export const demoContratos = [
  {
    id: "cont-1",
    numero: "CTR-2026-001",
    clienteNome: "Construtora Horizonte Ltda",
    tipo: "manutencao_preventiva",
    descricao: "Manutenção preventiva trimestral de toda infraestrutura TI + CFTV",
    status: "ativo",
    valorMensal: 1800,
    diaVencimento: 5,
    inicioVigencia: diasAtras(180),
    fimVigencia: diasAtras(-180),
    proximaVisita: diasAtras(-15),
    osGeradas: 4,
  },
  {
    id: "cont-2",
    numero: "CTR-2026-002",
    clienteNome: "Padaria Pão Quente",
    tipo: "suporte_tecnico",
    descricao: "Suporte técnico mensal para equipamentos de refrigeração e fornos",
    status: "ativo",
    valorMensal: 650,
    diaVencimento: 10,
    inicioVigencia: diasAtras(90),
    fimVigencia: diasAtras(-90),
    proximaVisita: diasAtras(-7),
    osGeradas: 2,
  },
  {
    id: "cont-3",
    numero: "CTR-2025-008",
    clienteNome: "Maria Aparecida Souza",
    tipo: "garantia_extendida",
    descricao: "Garantia estendida 12 meses para Notebook Dell",
    status: "expirado",
    valorMensal: 49.9,
    diaVencimento: 20,
    inicioVigencia: diasAtras(365),
    fimVigencia: diasAtras(0),
    proximaVisita: null,
    osGeradas: 1,
  },
];

/* ---------------------- Garantias ---------------------- */

export const demoGarantias = [
  {
    id: "gar-1",
    osNumero: "OS-2026-0038",
    clienteNome: "Ricardo Hoffmann",
    equipamentoNome: "Notebook Lenovo ThinkPad",
    descricao: "Garantia de reparo — troca de tela",
    prazoMeses: 6,
    dataEmissao: diasAtras(10),
    dataExpiracao: diasAtras(-170),
    status: "ativa",
    observacoes: "Garantia cobre somente o serviço realizado. Danos físicos não cobertos.",
  },
  {
    id: "gar-2",
    osNumero: "OS-2026-0040",
    clienteNome: "Construtora Horizonte Ltda",
    equipamentoNome: "DVR CFTV 16 canais",
    descricao: "Garantia de reparo — troca de HD e configuração",
    prazoMeses: 3,
    dataEmissao: diasAtras(5),
    dataExpiracao: diasAtras(-85),
    status: "ativa",
    observacoes: null,
  },
  {
    id: "gar-3",
    osNumero: "OS-2025-0112",
    clienteNome: "João Pedro Almeida",
    equipamentoNome: "MacBook Pro",
    descricao: "Garantia de reparo — troca de bateria",
    prazoMeses: 6,
    dataEmissao: diasAtras(200),
    dataExpiracao: diasAtras(20),
    status: "expirada",
    observacoes: null,
  },
  {
    id: "gar-4",
    osNumero: "OS-2026-0042",
    clienteNome: "Maria Aparecida Souza",
    equipamentoNome: "Notebook Dell Inspiron 15",
    descricao: "Garantia de reparo — troca DC Jack",
    prazoMeses: 3,
    dataEmissao: diasAtras(2),
    dataExpiracao: diasAtras(-88),
    status: "ativa",
    observacoes: "Válida somente para o serviço de solda do conector.",
  },
];

/* ---------------------- Agenda ---------------------- */

export const demoAgendaEventos = [
  // ---------- HOJE ----------
  {
    id: "ag-1",
    titulo: "Visita técnica — Construtora Horizonte",
    tipo: "visita_tecnica",
    status: "confirmado",
    prioridade: "alta",
    visibilidade: "todos",
    tecnicoId: "usr-2",
    tecnicoNome: "Carlos Mendes",
    clienteNome: "Construtora Horizonte Ltda",
    clienteTelefone: "(11) 3000-4000",
    osNumero: "OS-2026-0040",
    data: diasAtras(0),
    horaInicio: "09:00",
    horaFim: "12:00",
    endereco: "Av. Paulista, 1000 — São Paulo, SP",
    linkMaps: "https://maps.google.com",
    descricao: "Manutenção geral dos servidores e troca de cabos de rede.",
    observacoesInternas: "Cliente exige crachá de identificação na portaria.",
    checklist: [
      { id: "c1", texto: "Verificar racks do andar 3", concluido: true },
      { id: "c2", texto: "Testar cabeamento Cat6", concluido: false },
      { id: "c3", texto: "Emitir relatório de visita", concluido: false },
    ],
    notificacoes: [1440, 120, 30],
    cor: "#3b82f6",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(5),
  },
  {
    id: "ag-2",
    titulo: "Entrega — Ricardo Hoffmann",
    tipo: "entrega_equipamento",
    status: "finalizado",
    prioridade: "normal",
    visibilidade: "todos",
    tecnicoId: "usr-3",
    tecnicoNome: "Ana Ribeiro",
    clienteNome: "Ricardo Hoffmann",
    clienteTelefone: "(11) 91234-5678",
    osNumero: "OS-2026-0038",
    data: diasAtras(0),
    horaInicio: "14:00",
    horaFim: "15:00",
    endereco: null,
    descricao: "Entrega do notebook após reparo completo.",
    checklist: [
      { id: "c1", texto: "Testar equipamento na frente do cliente", concluido: true },
      { id: "c2", texto: "Assinar termo de entrega", concluido: true },
      { id: "c3", texto: "Registrar pagamento", concluido: true },
    ],
    notificacoes: [60, 15],
    cor: "#22c55e",
    criadoPor: "Pedro Atendente",
    criadoEm: diasAtras(3),
    finalizadoEm: diasAtras(0),
  },
  {
    id: "ag-6",
    titulo: "URGENTE — Servidor caiu na Padaria Pão Quente",
    tipo: "prioridade_urgente",
    status: "urgente",
    prioridade: "critica",
    visibilidade: "todos",
    tecnicoId: "usr-2",
    tecnicoNome: "Carlos Mendes",
    clienteNome: "Padaria Pão Quente",
    clienteTelefone: "(11) 94567-8901",
    data: diasAtras(0),
    horaInicio: "16:00",
    horaFim: "18:00",
    endereco: "Rua das Padarias, 50 — Osasco, SP",
    linkMaps: "https://maps.google.com",
    descricao: "Sistema de PDV fora do ar. Perda financeira em tempo real.",
    observacoesInternas: "Levar HD reserva e cabo de força extra.",
    checklist: [],
    notificacoes: [30, 0],
    cor: "#ef4444",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(0),
  },
  // ---------- AMANHÃ ----------
  {
    id: "ag-3",
    titulo: "Manutenção preventiva — contrato Padaria",
    tipo: "manutencao_preventiva",
    status: "agendado",
    prioridade: "normal",
    visibilidade: "todos",
    tecnicoId: "usr-2",
    tecnicoNome: "Carlos Mendes",
    clienteNome: "Padaria Pão Quente",
    clienteTelefone: "(11) 94567-8901",
    data: diasAtras(-1),
    horaInicio: "08:00",
    horaFim: "11:00",
    endereco: "Rua das Padarias, 50 — Osasco, SP",
    linkMaps: "https://maps.google.com",
    descricao: "Manutenção preventiva mensal incluída no contrato.",
    checklist: [
      { id: "c1", texto: "Limpar computadores internamente", concluido: false },
      { id: "c2", texto: "Verificar drives e temperatura", concluido: false },
      { id: "c3", texto: "Backup dos dados", concluido: false },
      { id: "c4", texto: "Atualizar sistema operacional", concluido: false },
    ],
    notificacoes: [1440, 120],
    cor: "#f59e0b",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(15),
  },
  {
    id: "ag-4",
    titulo: "Atendimento — Fernanda Costa Lima",
    tipo: "atendimento_remoto",
    status: "agendado",
    prioridade: "normal",
    visibilidade: "todos",
    tecnicoId: "usr-3",
    tecnicoNome: "Ana Ribeiro",
    clienteNome: "Fernanda Costa Lima",
    clienteTelefone: "(11) 97654-3210",
    osNumero: "OS-2026-0039",
    data: diasAtras(-1),
    horaInicio: "10:00",
    horaFim: "11:30",
    endereco: null,
    descricao: "Atendimento remoto para diagnóstico do Samsung S22.",
    checklist: [],
    notificacoes: [60, 15],
    cor: "#8b5cf6",
    criadoPor: "Pedro Atendente",
    criadoEm: diasAtras(2),
  },
  // ---------- PRÓXIMOS DIAS ----------
  {
    id: "ag-5",
    titulo: "Reunião de equipe semanal",
    tipo: "reuniao",
    status: "agendado",
    prioridade: "baixa",
    visibilidade: "todos",
    tecnicoNome: null,
    clienteNome: null,
    data: diasAtras(-2),
    horaInicio: "08:30",
    horaFim: "09:30",
    endereco: "Loja — sala de reunião",
    descricao: "Review semanal: OS em aberto, metas e prioridades.",
    checklist: [
      { id: "c1", texto: "Apresentar painel de OS atrasadas", concluido: false },
      { id: "c2", texto: "Definir técnico para visitas da semana", concluido: false },
    ],
    notificacoes: [30],
    cor: "#6b7280",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(8),
  },
  {
    id: "ag-7",
    titulo: "Instalação — Clínica Dental Prime",
    tipo: "instalacao",
    status: "agendado",
    prioridade: "alta",
    visibilidade: "todos",
    tecnicoId: "usr-2",
    tecnicoNome: "Carlos Mendes",
    clienteNome: "Clínica Dental Prime",
    clienteTelefone: "(11) 3200-5555",
    data: diasAtras(-3),
    horaInicio: "07:30",
    horaFim: "13:00",
    endereco: "Av. Brigadeiro Faria Lima, 3000 — São Paulo, SP",
    linkMaps: "https://maps.google.com",
    descricao: "Instalação completa de rede Wi-Fi e 6 computadores novos.",
    observacoesInternas: "Material já foi comprado. Caixas estão na loja.",
    checklist: [
      { id: "c1", texto: "Montar e conectar 6 computadores", concluido: false },
      { id: "c2", texto: "Configurar roteador e rede", concluido: false },
      { id: "c3", texto: "Instalar softwares odontológicos", concluido: false },
      { id: "c4", texto: "Treinamento básico equipe clínica", concluido: false },
    ],
    notificacoes: [1440, 120, 30],
    cor: "#0ea5e9",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(7),
  },
  {
    id: "ag-8",
    titulo: "Diagnóstico — João Pedro Almeida",
    tipo: "diagnostico",
    status: "agendado",
    prioridade: "normal",
    visibilidade: "todos",
    tecnicoId: "usr-3",
    tecnicoNome: "Ana Ribeiro",
    clienteNome: "João Pedro Almeida",
    clienteTelefone: "(11) 91234-5678",
    osNumero: "OS-2026-0041",
    data: diasAtras(-3),
    horaInicio: "14:00",
    horaFim: "16:00",
    endereco: null,
    descricao: "Diagnóstico completo iPhone 13 Pro — tela e bateria.",
    checklist: [],
    notificacoes: [60],
    cor: "#10b981",
    criadoPor: "Pedro Atendente",
    criadoEm: diasAtras(1),
  },
  {
    id: "ag-9",
    titulo: "Retorno garantia — Maria Aparecida",
    tipo: "retorno_garantia",
    status: "agendado",
    prioridade: "alta",
    visibilidade: "todos",
    tecnicoId: "usr-2",
    tecnicoNome: "Carlos Mendes",
    clienteNome: "Maria Aparecida Souza",
    clienteTelefone: "(11) 98765-4321",
    osNumero: "OS-2026-0042",
    data: diasAtras(-5),
    horaInicio: "11:00",
    horaFim: "12:00",
    endereco: null,
    descricao: "Retorno para verificar serviço de DC Jack — garantia ativa.",
    checklist: [],
    notificacoes: [1440, 30],
    cor: "#f97316",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(3),
  },
  {
    id: "ag-10",
    titulo: "Cobrança — Farmácia São Jorge",
    tipo: "cobranca",
    status: "aguardando_cliente",
    prioridade: "alta",
    visibilidade: "gerente",
    tecnicoId: "usr-4",
    tecnicoNome: "Pedro Atendente",
    clienteNome: "Farmácia São Jorge",
    data: diasAtras(-4),
    horaInicio: "09:00",
    horaFim: "09:30",
    endereco: "Rua da Saúde, 200 — São Paulo, SP",
    descricao: "Cobrança de contrato em aberto — 2 mensalidades pendentes.",
    observacoesInternas: "Falar diretamente com o gerente Alexandre.",
    checklist: [],
    notificacoes: [1440],
    cor: "#dc2626",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(6),
  },
  {
    id: "ag-11",
    titulo: "Retirada — Notebook Construtora",
    tipo: "retirada_equipamento",
    status: "confirmado",
    prioridade: "normal",
    visibilidade: "todos",
    tecnicoId: "usr-3",
    tecnicoNome: "Ana Ribeiro",
    clienteNome: "Construtora Horizonte Ltda",
    data: diasAtras(-6),
    horaInicio: "08:00",
    horaFim: "09:00",
    endereco: "Av. Paulista, 1000 — São Paulo, SP",
    descricao: "Retirar notebook Dell para reparo da tela.",
    checklist: [
      { id: "c1", texto: "Fotografar estado externo do equipamento", concluido: false },
      { id: "c2", texto: "Assinar termo de recebimento", concluido: false },
    ],
    notificacoes: [120, 30],
    cor: "#0891b2",
    criadoPor: "Pedro Atendente",
    criadoEm: diasAtras(8),
  },
  {
    id: "ag-12",
    titulo: "Lembrete — Renovar contrato InfoFix",
    tipo: "lembrete",
    status: "agendado",
    prioridade: "normal",
    visibilidade: "admin",
    data: diasAtras(-7),
    horaInicio: "10:00",
    horaFim: "10:15",
    descricao: "Contrato vence em 30 dias. Enviar proposta de renovação.",
    checklist: [],
    notificacoes: [1440],
    cor: "#7c3aed",
    criadoPor: "Administrador (Demo)",
    criadoEm: diasAtras(0),
  },
];

/* ---------------------- Transações ---------------------- */

export const demoTransacoes = [
  { id: "t1", descricao: "OS-2026-0038 - Ricardo Hoffmann", tipo: "receita", categoria: "Mão de obra", valor: 650, data: diasAtras(2), status: "pago" },
  { id: "t2", descricao: "Aluguel do galpão — Junho", tipo: "despesa", categoria: "Aluguel", valor: 2500, data: diasAtras(3), status: "pago" },
  { id: "t3", descricao: "OS-2026-0040 - Construtora Horizonte", tipo: "receita", categoria: "Mão de obra", valor: 1200, data: diasAtras(4), status: "pendente" },
  { id: "t4", descricao: "Compra de peças - Display iPhone", tipo: "despesa", categoria: "Peças/Insumos", valor: 480, data: diasAtras(5), status: "pago" },
  { id: "t5", descricao: "OS-2026-0041 - João Pedro Almeida", tipo: "receita", categoria: "Mão de obra", valor: 280, data: diasAtras(6), status: "pendente" },
  { id: "t6", descricao: "Salário - Carlos Mendes", tipo: "despesa", categoria: "Pessoal", valor: 3200, data: diasAtras(7), status: "pago" },
  { id: "t7", descricao: "Contrato mensal - Construtora Horizonte", tipo: "receita", categoria: "Contratos", valor: 1800, data: diasAtras(8), status: "pago" },
  { id: "t8", descricao: "Contrato mensal - Padaria Pão Quente", tipo: "receita", categoria: "Contratos", valor: 650, data: diasAtras(9), status: "pago" },
  { id: "t9", descricao: "Internet + Telefone", tipo: "despesa", categoria: "Utilidades", valor: 280, data: diasAtras(10), status: "pago" },
  { id: "t10", descricao: "OS-2026-0035 - Roberto Mota", tipo: "receita", categoria: "Mão de obra", valor: 320, data: diasAtras(12), status: "pago" },
  { id: "t11", descricao: "Salário - Ana Ribeiro", tipo: "despesa", categoria: "Pessoal", valor: 2800, data: diasAtras(14), status: "pago" },
  { id: "t12", descricao: "OS-2026-0033 - Patrícia Nunes", tipo: "receita", categoria: "Mão de obra", valor: 190, data: diasAtras(16), status: "pago" },
];

/* ---------------------- OS Detalhe (demo) ---------------------- */

export const demoOSDetalhe = {
  id: "os-1",
  numero: "OS-2026-0042",
  empresa_id: "demo-empresa",
  status: "em_reparo",
  prioridade: "alta",
  origem: "presencial",
  problema: "Cliente relata que o notebook não liga. Testado com carregador original e o LED de carga não acende. Possível problema na placa-mãe ou conector de carga.",
  diagnostico: "Conector de carga com mau contato. Solda fria identificada na entrada DC Jack. Tensão de entrada chegando mas não passando para o circuito de carga.",
  solucao: null,
  acessorios: ["Carregador original", "Mochila"],
  condicao_visual: "bom",
  senha_equip: null,
  obs_internas: "Cliente é VIP — priorizar. Atender pessoalmente quando pronto.",
  observacoes: null,
  valor_mao_obra: 180,
  valor_pecas: 45,
  valor_desconto: 0,
  valor_total: 225,
  garantia_dias: 90,
  garantia_expira: null,
  portal_token: "demo-token-abc123",
  data_abertura: diasAtras(2),
  data_previsao: diasAtras(-1),
  data_aprovacao: null,
  data_fechamento: null,
  data_entrega: null,
  created_at: diasAtras(2),
  updated_at: diasAtras(0),
  clientes: {
    id: "cli-1",
    nome: "Maria Aparecida Souza",
    telefone: "(11) 98765-4321",
    whatsapp: "(11) 98765-4321",
    email: "maria.souza@email.com",
    cpf_cnpj: "123.456.789-00",
    endereco: "Rua das Flores, 123",
    cidade: "São Paulo",
    estado: "SP",
  },
  equipamentos: {
    id: "equip-1",
    nome: "Notebook Dell Inspiron 15",
    marca: "Dell",
    modelo: "Inspiron 15 3000",
    numero_serie: "SN-DELL-12345",
    imei: null,
    cor: "Preto",
  },
  usuarios: {
    id: "tec-1",
    nome: "Carlos Mendes",
    email: "carlos@techrepair.com",
    avatar_url: null,
  },
  os_itens: [
    { id: "item-1", tipo: "servico" as const, descricao: "Diagnóstico e mão de obra", quantidade: 1, valor_unit: 180, valor_total: 180 },
    { id: "item-2", tipo: "peca" as const, descricao: "DC Jack Notebook Dell 7.4mm", quantidade: 1, valor_unit: 45, valor_total: 45 },
  ],
  os_eventos: [
    {
      id: "ev-1",
      tipo: "criacao",
      descricao: "Ordem de serviço criada",
      metadata: {},
      created_at: diasAtras(2),
      usuarios: { nome: "Admin (Demo)", avatar_url: null },
    },
    {
      id: "ev-2",
      tipo: "status_alterado",
      descricao: 'Status alterado de "aberta" para "em_diagnostico"',
      metadata: { status_anterior: "aberta", status_novo: "em_diagnostico" },
      created_at: diasAtras(1),
      usuarios: { nome: "Carlos Mendes", avatar_url: null },
    },
    {
      id: "ev-3",
      tipo: "diagnostico_atualizado",
      descricao: "Diagnóstico atualizado",
      metadata: {},
      created_at: diasAtras(1),
      usuarios: { nome: "Carlos Mendes", avatar_url: null },
    },
    {
      id: "ev-4",
      tipo: "status_alterado",
      descricao: 'Status alterado de "em_diagnostico" para "em_reparo"',
      metadata: { status_anterior: "em_diagnostico", status_novo: "em_reparo" },
      created_at: diasAtras(0),
      usuarios: { nome: "Carlos Mendes", avatar_url: null },
    },
    {
      id: "ev-5",
      tipo: "comentario",
      descricao: "Aguardando chegada do DC Jack. Peça pedida ao fornecedor, prazo de 2 dias.",
      metadata: { usuario_nome: "Carlos Mendes" },
      created_at: diasAtras(0),
      usuarios: { nome: "Carlos Mendes", avatar_url: null },
    },
  ],
  os_fotos: [],
};

/* ---------------------- Helpers de labels/status ---------------------- */

export const statusOSConfig: Record<
  StatusOS,
  { label: string; color: string; bg: string }
> = {
  aberta: { label: "Aberta", color: "var(--color-fg-muted)", bg: "var(--color-surface-muted)" },
  em_diagnostico: { label: "Em diagnóstico", color: "var(--color-info)", bg: "var(--color-info-bg)" },
  aguardando_aprovacao: { label: "Aguard. aprovação", color: "var(--color-warning)", bg: "var(--color-warning-bg)" },
  em_reparo: { label: "Em reparo", color: "var(--color-brand-600)", bg: "var(--color-brand-50)" },
  aguardando_pecas: { label: "Aguard. peças", color: "var(--color-warning)", bg: "var(--color-warning-bg)" },
  pronto: { label: "Pronto", color: "var(--color-success)", bg: "var(--color-success-bg)" },
  entregue: { label: "Entregue", color: "var(--color-success)", bg: "var(--color-success-bg)" },
  cancelada: { label: "Cancelada", color: "var(--color-danger)", bg: "var(--color-danger-bg)" },
};

export const prioridadeOSConfig: Record<
  PrioridadeOS,
  { label: string; color: string }
> = {
  baixa: { label: "Baixa", color: "var(--color-fg-subtle)" },
  media: { label: "Média", color: "var(--color-info)" },
  alta: { label: "Alta", color: "var(--color-warning)" },
  urgente: { label: "Urgente", color: "var(--color-danger)" },
};

export const roleConfig: Record<string, { label: string; color: string; bg: string }> = {
  admin: { label: "Administrador", color: "var(--color-brand-700)", bg: "var(--color-brand-50)" },
  gerente: { label: "Gerente", color: "var(--color-info)", bg: "var(--color-info-bg)" },
  tecnico: { label: "Técnico", color: "var(--color-success)", bg: "var(--color-success-bg)" },
  atendente: { label: "Atendente", color: "var(--color-fg-muted)", bg: "var(--color-surface-muted)" },
  financeiro: { label: "Financeiro", color: "var(--color-warning)", bg: "var(--color-warning-bg)" },
  cliente: { label: "Cliente", color: "var(--color-fg-subtle)", bg: "var(--color-surface-muted)" },
  super_admin: { label: "Super Admin", color: "var(--color-danger)", bg: "var(--color-danger-bg)" },
};
